Create UI Structure
hannessolo/app-builder-trial-form-nextjs pull request #1
Opened 2022-04-11 14:35 UTC by hannessolo

2022-04-12 10:43 UTC, icaraps requested changes
LGTM ! There's one thing major I'd like to change if possible. Could you think of a way to extract the raw data (questions, responses, text) into another file (eg json) to separate the layout from the actual data ? 
I also noticed a few spacing issues eg on slide 2 between the select and the buttons. Or alignment issues, eg radio boxes are not vertically aligned. 
In general, I think it would make sense to increase the container width and add more spacing while making sure it's responsive.

2022-04-12 10:43 UTC, icaraps commented on pages/_app.tsx
> +            <Provider theme={defaultTheme}>
Can you pls use the light theme ? As the parent shell is also using the light theme by default

2022-04-12 10:43 UTC, icaraps commented on .gitignore
> +.idea
This can be added in your global gitignore so it's not required here

2022-04-12 10:43 UTC, icaraps commented on Slides/SummarySlide.tsx
> +    <h1>Ok, thanks User</h1>
Can you use spectrum's typography instead here ? You'll have to import the css package https://opensource.adobe.com/spectrum-css/typography.html 
We'll also add the adobe font later.

2022-04-12 10:43 UTC, icaraps commented on Slides/SummarySlide.tsx
> +    <span>Here’s what we will record for your trial:</span>
Can you use a layout component here to display the data ?

2022-04-12 10:43 UTC, icaraps commented on components/Slides.module.css
> +.actionButtonContainer > * {
Maybe you can be more specific in your selector here

2022-04-12 20:41 UTC, hannessolo commented on Slides/SummarySlide.tsx
> +    <h1>Ok, thanks User</h1>
I'm not sure how to do this, I don't think I can import that library into nextjs?

2022-04-12 20:59 UTC, hannessolo commented
- I improved the layout somewhat, but will wait before doing more in case Ron decides to change it, and focus on functionality first
- I'm not sure how to import the css typography library you commented
- I extracted the long strings, but won't do smaller ones yet, because I have a branch where I changed some of these - so I don't have to do it all twice
- I will move the repo to git corp once we merge this

2022-04-13 07:54 UTC, icaraps approved these changes

2022-04-13 08:48 UTC, merged